apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: tax-calculator-run
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: repo-url
      value: https://github.com/samikhaled-sys/tax-calculator-devops
  workspaces:
    - name: shared-workspace
      emptyDir: {}
